spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
    session:
      timeout: 30m

logging:
  level:
    com.jinmifood.jinmi: trace
    org.springframework.security: debug