server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 15m

spring:
  application:
    name: jinmifood
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true

logging:
  level:

    com.jinmifood.jinmi: info
    org.springframework.security: info


summarization:
  chunk:
    size: 1500

jwt:
  secret: VGhpc0lzTXlTdXBlclNlY3VyZUtleUZvckppbm1pRm9vZFNlcnZpY2U=
  access-token-expiration-time: 1800000 #(30분)

