server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 15m

spring:
  config:
    import: optional:application-secret.yml
  profiles:
    active: dev
    include: secret
  application:
    name: jinmifood
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        charset: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true

jwt:
  access-token-expiration-time: 10000
  refresh-token-expiration-time: 604800000

logging:
  level:
    com.jinmifood.jinmi: debug
    org.springframework.security: debug



summarization:
  chunk:
    size: 1500



